import type { BusinessConfig } from '../business.types'
import { demoElectricianConfig } from './demo-electrician.config'

/**
 * Client configuration registry
 *
 * For demo sites: Uses demo-electrician config
 * For client sites: Uses client.config.ts (generated by setup script)
 */
export const clients: Record<string, BusinessConfig> = {
  'demo-electrician': demoElectricianConfig,
  // Client config is added here by setup script:
  // 'client': clientConfig,
}

/**
 * Get client config by slug
 */
export function getClientConfig(slug?: string): BusinessConfig {
  if (slug && clients[slug]) {
    return clients[slug]
  }
  // Default to demo-electrician
  return demoElectricianConfig
}

/**
 * Get client config by custom domain
 */
export function getClientConfigByDomain(domain: string): BusinessConfig | null {
  return (
    Object.values(clients).find((config) => config.customDomain === domain) ||
    null
  )
}

/**
 * Get all client configs
 */
export function getAllClients(): BusinessConfig[] {
  return Object.values(clients)
}

/**
 * Get the default/main config for this site
 */
export function getDefaultConfig(): BusinessConfig {
  return demoElectricianConfig
}
